Задание 1
Скачайте с сайта https://grouplens.org/datasets/movielens/ датасет любого размера. Определите какому фильму было выставлено больше всего оценок 5.0.

In [2]:
import pandas

In [11]:
df = pandas.read_csv("ratings.csv")

In [12]:
df[df["rating"].eq(5)].groupby("movieId").size().sort_values(ascending=False).head()

movieId
318    48762
296    37458
356    32009
260    31385
593    30280
dtype: int64

Задание 2
По данным файла power.csv посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 года. Не учитывайте в расчетах отрицательные значения quantity.

In [8]:
df = pandas.read_csv("power.csv")


df1 = df[(df["category"].isin([4,12,21])) & (df["country"].isin(["Latvia","Lithuania","Estonia"])) & (df["year"].between(2005,2010))& (df["quantity"]>=0)]
df1["quantity"].sum()

240580.0

Задание 3
Выберите страницу любого сайта с табличными данными. Импортируйте таблицы в pandas dataframe.
Примеры страниц (необязательно брать именно эти):
https://fortrader.org/quotes
https://www.finanz.ru/valyuty/v-realnom-vremeni

In [6]:
df = pandas.read_html('https://www.finanz.ru/valyuty/v-realnom-vremeni')[1]
df

,Unnamed: 0,а баБаЛб,абаЕаДаЛаОаЖаЕаНаИаЕ,аЁаПбаОб,абаЕаДбаДббаЕаЕ аЗаАаКбббаИаЕ,%,ааБбаОаЛббаНаОаЕ аЗаНаАбаЕаНаИаЕ,абаЕаМб
0,NaN,GBP/RUB,1006495,-,1006495,"0,00 %",00000,17.10.2020
1,NaN,EUR/RUB,911850,-,911850,"0,00 %",00000,17.10.2020
2,NaN,USD/RUB,779262,-,779745,"-0,06 %",-00483,17.10.2020
3,NaN,JPY/RUB,07393,-,07394,"0,00 %",00000,17.10.2020
4,NaN,CNY/RUB,116347,-,116349,"0,00 %",-00003,17.10.2020
5,NaN,CHF/RUB,851960,-,851839,"0,01 %",00121,17.10.2020
6,NaN,ааВбаО,абаЕаДаЛаОаЖаЕаНаИаЕ,аЁаПбаОб,абаЕаДбаДббаЕаЕ аЗаАаКбббаИаЕ,%,ааБбаОаЛббаНаОаЕ аЗаНаАбаЕаНаИаЕ,абаЕаМб
7,NaN,EUR/USD,11717,-,11710,"0,06 %",00007,17.10.2020
8,NaN,EUR/GBP,09072,-,09072,"0,00 %",00000,17.10.2020
9,NaN,EUR/JPY,1235150,-,1235000,"0,01 %",00150,17.10.2020
10,NaN,EUR/CHF,10743,-,10709,"0,32 %",00034,17.10.2020
11,NaN,ааОаЛаЛаАб аЁаЈа,абаЕаДаЛаОаЖаЕаНаИаЕ,аЁаПбаОб,абаЕаДбаДббаЕаЕ аЗаАаКбббаИаЕ,%,ааБбаОаЛббаНаОаЕ аЗаНаАбаЕаНаИаЕ,абаЕаМб
12,NaN,USD/EUR,08535,-,08535,"0,00 %",00000,17.10.2020
13,NaN,USD/GBP,07742,-,07742,"0,00 %",00000,17.10.2020
14,NaN,USD/JPY,1054000,-,1054000,"0,00 %",00000,17.10.2020
15,NaN,USD/CHF,09147,-,09148,"-0,01 %",-00001,17.10.2020
16,NaN,аЏаПаОаНбаКаАб аИаЕаНаА,абаЕаДаЛаОаЖаЕаНаИаЕ,аЁаПбаОб,абаЕаДбаДббаЕаЕ аЗаАаКбббаИаЕ,%,ааБбаОаЛббаНаОаЕ аЗаНаАбаЕаНаИаЕ,абаЕаМб
17,NaN,JPY/EUR (100:1),08100,-,08100,"0,00 %",00000,17.10.2020
18,NaN,JPY/GBP,00074,-,00074,"0,00 %",00000,17.10.2020
19,NaN,JPY/USD,00095,-,00095,"0,00 %",00000,17.10.2020
20,NaN,JPY/CHF (100:1),08700,-,08700,"0,07 %",00000,17.10.2020
21,NaN,аЄбаНб ббаЕбаЛаИаНаГаОаВ,абаЕаДаЛаОаЖаЕаНаИаЕ,аЁаПбаОб,абаЕаДбаДббаЕаЕ аЗаАаКбббаИаЕ,%,ааБбаОаЛббаНаОаЕ аЗаНаАбаЕаНаИаЕ,абаЕаМб
22,NaN,GBP/USD,12916,-,12916,"0,00 %",00000,17.10.2020
23,NaN,GBP/JPY,1361347,-,1361282,"0,00 %",00065,17.10.2020
24,NaN,GBP/EUR,11022,-,11024,"-0,02 %",-00003,17.10.2020
25,NaN,GBP/CHF,11815,-,11814,"0,00 %",00001,17.10.2020
26,NaN,аЈаВаЕаЙбаАббаКаИаЙ ббаАаНаК,абаЕаДаЛаОаЖаЕаНаИаЕ,аЁаПбаОб,абаЕаДбаДббаЕаЕ аЗаАаКбббаИаЕ,%,ааБбаОаЛббаНаОаЕ аЗаНаАбаЕаНаИаЕ,абаЕаМб
27,NaN,GBP/CHF,11815,-,11814,"0,00 %",00001,17.10.2020
28,NaN,EUR/CHF,10743,-,10709,"0,32 %",00034,17.10.2020
29,NaN,JPY/CHF (100:1),08700,-,08700,"0,07 %",00000,17.10.2020
30,NaN,USD/CHF,09147,-,09148,"-0,01 %",-00001,17.10.2020
31,NaN,аЃаКбаАаИаНбаКаАб аГбаИаВаНаА,абаЕаДаЛаОаЖаЕаНаИаЕ,аЁаПбаОб,абаЕаДбаДббаЕаЕ аЗаАаКбббаИаЕ,%,ааБбаОаЛббаНаОаЕ аЗаНаАбаЕаНаИаЕ,абаЕаМб
32,NaN,EUR/UAH,331990,-,332298,"-0,09 %",-00307,17.10.2020
33,NaN,USD/UAH,283353,-,283615,"-0,09 %",-00263,17.10.2020
34,NaN,CHF/UAH,309788,-,310030,"-0,08 %",-00242,17.10.2020
35,NaN,GBP/UAH,365980,-,366317,"-0,09 %",-00338,17.10.2020

Задание 4
Напишите функцию, которая классифицирует фильмы из материалов занятия по следующим правилам:
- оценка 2 и меньше - низкий рейтинг
- оценка 4 и меньше - средний рейтинг
- оценка 4.5 и 5 - высокий рейтинг

Результат классификации запишите в столбец class

In [ ]:
import numpy
df = pandas.read_csv("ratings.csv")
def set_tier(row):
    conditions = [
    (row['rating'] <= 2),
    (row['rating'] > 2) & (row['rating'] < 4.5),
    (row['rating'] >= 4.5)
    ]
    values = ['low_tier','mid_tier', 'high_tier']
    return numpy.select(conditions,values)
df['tier'] = df.apply(set_tier, axis=1)
df

Задание 5
Используем файл keywords.csv.

Необходимо написать гео-классификатор, который каждой строке сможет выставить географическую принадлежность определенному региону. Т. е. если поисковый запрос содержит название города региона, то в столбце ‘region’ пишется название этого региона. Если поисковый запрос не содержит названия города, то ставим ‘undefined’.

Правила распределения по регионам Центр, Северо-Запад и Дальний Восток:

geo_data = {
'Центр': ['москва', 'тула', 'ярославль'],
'Северо-Запад': ['петербург', 'псков', 'мурманск'],
'Дальний Восток': ['владивосток', 'сахалин', 'хабаровск']
}

Результат классификации запишите в отдельный столбец region.

In [12]:
import numpy
import pandas
df = pandas.read_csv("keywords.csv")

def classify(row):
    if 'москва' in row['keyword'] or 'тула' in row['keyword'] or 'ярославль' in row['keyword']:
        return 'Центр'
    elif 'петербург' in row['keyword'] or 'псков' in row['keyword'] or 'псков' in row['keyword']:
        return 'Северо-Запад'
    elif 'владивосток' in row['keyword'] or 'сахалин' in row['keyword'] or 'хабаровск' in row['keyword']:
        return 'Дальний Восток'
    else:
        return 'undefined'
# create
df['region'] = df.apply(classify, axis=1)
df['region'].value_counts()

undefined         99281
Центр               387
Северо-Запад        238
Дальний Восток       94
Name: region, dtype: int64

Задание 6
Есть мнение, что “раньше снимали настоящее кино, не то что сейчас”. Ваша задача проверить это утверждение, используя файлы с рейтингами фильмов из прошлого домашнего занятия (файл ratings.csv из базы https://grouplens.org/datasets/movielens). Т. е. проверить верно ли, что с ростом года выпуска фильма его средний рейтинг становится ниже.

При этом мы не будем затрагивать субьективные факторы выставления этих рейтингов, а пройдемся по следующему алгоритму:

В переменную years запишите список из всех годов с 1950 по 2010.

Напишите функцию production_year, которая каждой строке из названия фильма выставляет год выпуска. Не все названия фильмов содержат год выпуска в одинаковом формате, поэтому используйте следующий алгоритм:

для каждой строки пройдите по всем годам списка years
если номер года присутствует в названии фильма, то функция возвращает этот год как год выпуска
если ни один из номеров года списка years не встретился в названии фильма, то возвращается 1900 год
Запишите год выпуска фильма по алгоритму пункта 2 в новый столбец ‘year’

Посчитайте средний рейтинг всех фильмов для каждого значения столбца ‘year’ и отсортируйте результат по убыванию рейтинга

In [6]:
import pandas
mov = pandas.read_csv('movies.csv')
rat = pandas.read_csv('ratings.csv')

merged_db = rat.merge(mov, how='left')

rating = merged_db.groupby('title').mean().reset_index()[['title', 'rating']]

rating.head()

                              title    rating
0  "Great Performances" Cats (1998)  2.815556
1        #1 Cheerleader Camp (2010)  2.777778
2                  #Captured (2017)  2.500000
3                    #Horror (2015)  2.078947
4                 #SCREAMERS (2016)  2.500000

In [7]:
years = [str(i) for i in range(1950,2010)]
def movie_year(row):
    for year in years:
        if year in row['title']:
            return year
    return '1900'

In [8]:
rating['year'] = rating.apply(movie_year, axis=1)
rating.head(10)

                                               title    rating  year
0                   "Great Performances" Cats (1998)  2.815556  1998
1                         #1 Cheerleader Camp (2010)  2.777778  1900
2                                   #Captured (2017)  2.500000  1900
3                                     #Horror (2015)  2.078947  1900
4                                  #SCREAMERS (2016)  2.500000  1900
5  #chicagoGirl: The Social Network Takes on a Di...  3.000000  1900
6                                #realityhigh (2017)  3.361111  1900
7                                 $ (Dollars) (1971)  2.781250  1971
8                         $1,000 on the Black (1966)  3.333333  1966
9                          $100,000 for Ringo (1965)  2.500000  1965

In [9]:
rating.sort_values('rating', ascending=False).head(100)

                                            title  rating  year
50501                       VHS Revolution (2017)     5.0  1900
51532                     We Are Mountains (1969)     5.0  1969
13333        Dragon Lee Vs. The 5 Brothers (1978)     5.0  1978
26316                       Living on Love (1937)     5.0  1900
8644                       Change of Plans (2011)     5.0  1900
...                                           ...     ...   ...
17783  Give Me Future: Major Lazer in Cuba (2017)     5.0  1900
4957                       Beatles Stories (2011)     5.0  1900
27322      Maciste in Hell of Genghis Khan (1964)     5.0  1964
44113                     The Dreamed Ones (2016)     5.0  1900
18049                     Going to the Mat (2004)     5.0  2004

[100 rows x 3 columns]

Таким образом, среди старых фильмов высокие оценки встречаются заметно чаще, следовательно, данное выражение имеет смысл.